# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jialu Bao (鲍家路)
# email: your-email@example.com
description: Jialu's notes and blog # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "jialujialu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: "Jialu Bao"
  avatar: "/assets/images/bio-photo.jpeg"
  bio: "My first name is pronounced as J·ah·loo :D" # Note: Markdown is allowed
  location: "Ithaca, NY"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Howowhy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JialuJialu"
      # - label: "Medium"
      #   icon: "fab fa-fw fa-medium"
      #   url: "https://medium.com/@jialubao"
      # - label: "Linkedin"
      #   icon: "fab fa-fw fa-linkedin"
      #   url: "https://www.linkedin.com/in/jialu-bao/"
      # github_username:  JialuJialu

# Build settings
lsi: false
safe: true
sass:
  sass_dir: _sass
incremental: false
include: ['_pages']
markdown: kramdown
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes@4.24.0
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: posts
      author_profile: true
      permalink: /:categories/:title/      
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
